controller:
  overrideConfiguration:
    transaction.state.log.replication.factor: 1
    transaction.state.log.min.isr: 1
    offsets.topic.replication.factor: 1
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  external:
    protocol: PLAINTEXT